name: deploy

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: apiToken
          accountId: accountId
          command: pages deploy dist --project-name=my-project
